apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: predictor
  namespace: default
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: predictor
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
