apiVersion: v1
kind: Service
metadata:
  name: js-app
  namespace: default
  labels:
    app: js-app
spec:
  selector:
    app: js-app
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
