apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: js-app
  namespace: default
  labels:
    release: monitoring   # MUST match Helm release name
spec:
  selector:
    matchLabels:
      app: js-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
